### ISSUE TITLE
How can I contribute to this repo?

### ISSUE THREAD

**Issue by hackasaur** [unbellum/revive-engine#1]
Hi @unbellum,
I would like to contribute to this project. I really want to work on a 3D game engine. I'm new to rust but have some knowledge of 3d graphics in general. please let me know if there is anything.

I couldn't find your email id on your github profile so didn't have any other way to contact you other than raising an issue :)

**Comment by unbellum** [comment]
Hello @hackasaur!

I am just keeping this as a solo project for me to learn a new language. I really appreciate you for reaching out and I hope you are able to find a project to work on!
